nginx/conf.d/scalelite-ssl.template
The name 'SSL' is generic and conflicts with default configuration.
=> BBBSL-40: Rename SSL session cache

.gitlab-ci.yml
The tag images are built and pushed automatically, but the update to
the "latest" tag is on a manual trigger for now.
=> BBBSL-39: Build tag images and push 'latest' tag from gitlab-ci

app/models/recording.rb, lib/tasks/recordings.rake
Also log the backtrace when an import fails to assist debugging.
=> BBBSL-43: Fix reference to loop variable in recording metadata import

app/models/recording.rb
I got this error for the recording import:
```
ERROR -- : Failed to import recording: bad URI(is not URI?): "\n      https://node2.xxx/playback/presentation/2.0/playback.html?meetingId=asdfasdfasdfasdf-123123123\n    "
```
This is the `metadata.xml`:
```
<playback>
<format>presentation</format>
<link>
https://node2.xxx/playback/presentation/2.0/playback.html?meetingId=asdfasdfasdfasdf-123123123
</link>
<processing_time>13684</processing_time>
<duration>8167</duration>
<size>639990</size>
```
So probably the simple fix is to strip the newlines.
Thanks for this software! (Also my first dive into Ruby ever).
=> recording: strip whitespace around links in recording metadata

README.md, nginx/conf.d/scalelite-proxy.template, nginx/conf.d/scalelite-ssl.template, nginx/start
Creates a new nginx template and ENV variable for scalelite behind a proxy or load balancer.
=> BBBSL-53: NGINX now forces ssl enabled websites to use https

lib/tasks/status.rake
This patch sorts the status table by hostname making it much more
readable, especially if you have a large number of hosts.
Before:
```
% ./bin/rake status
HOSTNAME    STATE    STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS
a.xy      disabled  offline         0      0                0       0
y.xy      disabled  offline         0      0                0       0
c.xy      disabled  offline         0      0                0       0
r.xy      disabled  offline         0      0                0       0
z.xy      disabled  offline         0      0                0       0
```
After:
```
% ./bin/rake status
HOSTNAME    STATE    STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS
a.xy      disabled  offline         0      0                0       0
c.xy      disabled  offline         0      0 …
```
=> Sort Status Table

bigbluebutton/scalelite_post_publish.rb
This patch tries to create the spool directory if it does not exist.
Otherwise rsync will copy the archive to the name of the directory (not
into the directory) and will succeed in a somewhat broken state.
=> Ensure Spool Directory Exists

nginx/conf.d/scalelite-proxy.template, nginx/start
The docker container name is variable but the value by default is still scalelite-api
=> tweak for clustering scalelite behind proxy

app/controllers/bigbluebutton_api_controller.rb
This removes the need for an extra helper function that duplicates the
renderer for BBBError.
=> SL-67: recording_disabled: Use existing BBBError rendering

app/constraints/recording_constraint.rb, app/controllers/bigbluebutton_api_controller.rb, config/routes.rb, test/controllers/bigbluebutton_api_controller_test.rb
* Separate routes for each recording api should be configured when recordings are disabled.
* getRecordings and getMeetings response with disabled  condition has incorrect format.
=> SL-67 & SL-68 : Add separate routes for each recording api

README.md, lib/tasks/poll.rake
Test run with 4 bbb servers, polling interval 0 for 10000 times
with concurrency
real	3m36.787s
user	1m47.659s
sys	0m20.469s
without concurrency
real	11m2.587s
user	2m2.871s
sys	0m19.233s
=> SL-65 & SL-66: Run scalelite poller parallely and Make poller timeout configurable

README.md, app/controllers/bigbluebutton_api_controller.rb, app/controllers/concerns/api_helper.rb, config/application.rb, test/controllers/bigbluebutton_api_controller_test.rb
This fixes #439.
Simply making the timeouts shorter and allowing them to be configured to match the environment of a particular deployment should reduce the impact of attempting to make calls on unreachable/slow BigBlueButton servers.
In addition, the timeouts on servers that the poller has marked as offline are shortened, to avoid a pile-up of hanging threads on servers that we suspect aren't going to be able to respond.
=> SL-83: Make timeouts on requests to BBB api configurable

lib/recording_importer.rb
Handle recording importer, on automated deployments relying on ENV variables (especifically on kubernetes), as disabling recording  can cause a problem because the pod (or container) would be constantly crashing if the database is not set.
=> SL77:Disable recording importer

lib/tasks/poll.rake
This change was incorrectly included in #428 and causes the poll
interval to default to 0 when the scalelite poller is launched using a
means other than the provided docker startup script.
=> Revert poll rake task default interval change.

README.md, config/application.rb, lib/tasks/poll.rake
Change the algorithm for calculating the load on every server: 
New Logic: Server load calculation is now based on number of users, and the SL gives every meeting an assignment of 15 users when it starts, and then post that uses max(actual number of users, 15).
=> SL:70 Change logic for calculating server load

README.md, app/models/application_redis_record.rb, app/models/server.rb, config/application.rb, test/models/server_test.rb
Closes #469 
This is an updated version of #205 that solves the problems that PR had:
* The hostname as id is now checked for uniqueness.
* The setting is off by default for compatibility reasons.
=> Allow using server hostname as ID instead of UUID

dockerfiles/v1/bionic230-amazonlinux
Tiny needs to be installed from source on amazonlinux. But it turns out that the gpg server used `p80.pool.sks-keyservers.net` is no longer existent.
The end solution would be to add the key to the repo, but for the moment changing the repo to keyserver.ubuntu.com is doing the trick
https://github.com/krallin/tini/issues/124
=> SL-XX: GPG key used for tini fails when building amazonlinux image

bigbluebutton/scalelite_cron.sh, bigbluebutton/scalelite_post_publish.rb
This pull request adds a cron.daily job to delete sent recordings from the BigBlueButton server after 4 days.
=> SL-186: Added logic to delete recordings sent to scalelite after a few days

app/views/bigbluebutton_api/get_recordings.xml.builder, test/controllers/bigbluebutton_api_controller_test.rb
The issue is that going to the url of the recorded meeting from getRecordings() returns a 301 redirect that is non-https which violates the client's IT policy
=> SL-187:  Fix getRecordings() Redirect Issue

.rubocop.yml, README.md, app/controllers/application_controller.rb, app/controllers/bigbluebutton_api_controller.rb, app/controllers/concerns/bbb_errors.rb, app/controllers/concerns/cookie_same_site_compat.rb, app/controllers/playback_controller.rb, app/helpers/bigbluebutton_api_helper.rb, app/models/playback_format.rb, app/models/recording.rb, app/views/bigbluebutton_api/get_recordings.xml.builder, config/application.rb, config/routes.rb
Rewrite the protected recordings implementation to store one-time-use tokens in redis, and use cookies to handle access control to subresources.
The nginx configuration for this updated setup should have location blocks set up like this:
```
location ~  /\.(?!well-known).* {
deny all;
access_log off;
log_not_found off;
return 404;
}
location /health_check {
proxy_pass http://docker-scalelite-api;
include /etc/nginx/sites-common;
}
location / {
proxy_pass http://docker-scalelite-api;
include /etc/nginx/sites-common;
}
location /static-resource/ {
proxy_pass http://docker-scalelite-recordings/;
include /etc/nginx/sites-common;
internal;
}
location /playback {
proxy_pass http://docker-scalelite-recordings/;
include /etc/nginx/sites-common;
}
```
=> Protected recordings updates

README.md, app/controllers/bigbluebutton_api_controller.rb, config/application.rb, test/controllers/bigbluebutton_api_controller_test.rb
Prevent get_recordings api from returning all recordings when recordID not specified in the request
=> SL-188: Prevent get_recordings api from returning all recordings when recordID not specified in the request

app/controllers/concerns/api_helper.rb
Prevents polling task from raising unwanted "execution expired" errors which lead to servers being falsely detected as "offline" and eventually panicked. (see file lib/tasks/poll.rake lines 89-104)
Fixes issue reported on Stackoverflow : https://stackoverflow.com/questions/9939726/ruby-net-http-opening-connection-very-slow/27485369#27485369
=> SL-196: fix(poll) add dependency to fix DNS resolution timeout bug.

app/controllers/bigbluebutton_api_controller.rb, test/controllers/bigbluebutton_api_controller_test.rb
getRecordings filter to prevent requests with no parameters
=> SL-199: add getRecordings filter for meetingId/recordId

bin/start, db/migrate/20181123180008_init.rb
This adds a missing DB migration step and ensures that 'db:migrate'
on an existing but empty DB works as expected. The bin/start script,
which is used as a docker container entry point, now bootstraps or
migrates the DB on startup (inspired by greenlight).
=> SL- 209: Fix db:migrate task and auto-bootstrap DB in bin/start

lib/tasks/status.rake
Hi, currently you can't see which server has which current load value - which could differ from the meetings and/or attendee count. This PR adds a "load" column to `rake status`
=> add load column to rake status table

nginx/conf.d/scalelite.common
scalelite-nginx fails to respond to old recordings. 
Update deployment based on systemd with the new scalelite-nginx image. Old recordings created with a BBB server 2.0 or earlier, should now be played back.
=> SL-214: patch for fixing scalelite-nginx recording backward compatibility #686

nginx/conf.d/scalelite.common
scalelite-nginx fails to respond to old recordings. 
Update deployment based on systemd with the new scalelite-nginx image. Old recordings created with a BBB server 2.0 or earlier, should now be played back.
=> SL-214: patch for fixing scalelite-nginx recording backward compatibility

app/controllers/playback_controller.rb
The recording playback files might contain (static) javascript which is
blocked by rails default CSRF protection.
Disable the CSRF protection on this endpoint to fix the issue. This
shouldn't cause any significant safety issues, since xml and json files
with recording data are still protected by browser XSR handling.
Fixes #732
=> Skip forgery protection on playback resource

test/controllers/playback_controller_test.rb
This is far from a complete set of tests, but it covers #732 and also
asserts that resources from protected recordings are blocked when the
cookie is missing.
=> GIT-732: Add some tests for protected recording playback

app/controllers/playback_controller.rb, app/views/bigbluebutton_api/get_recordings.xml.builder, test/controllers/playback_controller_test.rb
The ability of disabling protected recordings was never implemented. This is a serious bug that affects backward compatibility.
1. Set PROTECTED_RECORDINGS_ENABLED=true
2. Start SL, and create a recording
3. after the recording is imported, verify that protected recording works by accessing the playback, copy the URL and paste it on a different browser. The response should be a 404
4. Set PROTECTED_RECORDINGS_ENABLED=false
5. Restart SL
6. verify that protected recording is now disabled by accessing the playback, copy the URL and paste it on a different browser. The response should now be the recording as in the main browser
=> GIT-735: protected recordings can now be disabled (closes #735)

nginx/start
The assignment to the variable was incorrectly prefixed with $, so it
wasn't getting set correctly; and besides that the variable wasn't
exported to the environment so the 'envsubst' tool wouldn't pick it up.
Note that since the shell used is /bin/sh (which can be 'dash' in some
distros), the more compatible form of using export separately from
setting the variable is used here.
The way the envsubst tool was being run was incorrect; the second time
it was run it would replace the file without setting the api port at
all. Fix that by substituting both variables in a single call to
envsubst.
Fixes #743
=> GIT-743: Fix setting SCALELITE_API_PORT env var in nginx config

lib/tasks/servers.rake
fixes #738 
If an argument is not passed into a rake task, it automatically defaults the value to `''` which means the optional parameters in the `sync_file` method are never used
=> Fixed servers:sync default args

Dockerfile, dockerfiles/v1/bionic240-alpine
After last security Snyk patch was applied the build of alpine docker images was broken. This is because alpine 15 comes with ruby 3 and some dependencies are still tied to 2.7.
While the version of ruby must be updated, as a work around we install 2.7.6 from sources.
=> SL-243 updates to alpine base docker image after last security patch 

Dockerfile
Copy `nginx/conf.d` to docker image. The corresponding line was removed in f71012d1 prior to 1.3.5 breaking docker deployments. See #845
=> Fix #845 Nginx - Connection refused

spec/redis_helper.rb
Removes the following warning:
Redis.current is deprecated and will be removed in 5.0. (called from: /home/ubuntu/scalelite/spec/redis_helper.rb:9:in `block in included').
=> SL-273: Replace depreciated Redis.current method

app/controllers/bigbluebutton_api_controller.rb, app/controllers/errors_controller.rb, config/routes.rb, spec/requests/bigbluebutton_api_controller_spec.rb
fixes #941 
Adds support for the `insertDocument` BigBlueButton Api call: https://docs.bigbluebutton.org/development/api#insertdocument
Assuming you have a meetingID=random-195645, you can run the following command:
```
curl -s -X POST "http://localhost:4000/bigbluebutton/api/insertDocument?meetingID=random-195645&checksum=7cf422cc7e509f5ac578617e2d057058ce2f091a" --header "Content-Type: application/xml" --data '<modules>
<module name="presentation">
<document current="true" downloadable="true" url="{link to download the presentation}" filename="sample.pdf"/>
<document removable="false" name="sample.pdf"> 
JVBERi0xLjQKJdPr6eEKMSAwIG9iago8PC9UaXRsZSAoT3RoZXJfc2FtcGxlKQovUHJvZHVjZXIgKFNraWEvUERGIG0xMDAgR29vZ2xlIERvY3MgUmVuZGVyZXIpPj4KZW5
</document>
</module>
</modules>'
```
=> SL-281: Added support for insertDocument

.rubocop.yml, app/controllers/api/servers_controller.rb, app/controllers/api/tenants_controller.rb, app/controllers/concerns/api_helper.rb, config/routes.rb, spec/requests/servers_controller_spec.rb, spec/requests/tenants_controller_spec.rb
Changed the tenants and servers API to match the format for BBB, and added a checksum verification. 
The checksum must be computed with the LOADBALANCER_SECRET rather than the tenant's secret(s), so that tenants do not have access to all tenant and server information.
Use API Mate to create the custom calls.
=> SL-252,SL-248: Add checksum verification to servers, tenants API

Gemfile, Gemfile.lock, app/models/meeting.rb, app/models/server.rb, app/models/tenant.rb, spec/models/server_spec.rb
Updated the redis-namespace gem from version 1.10 to version 1.11.0. This update allows for redis' srem function to be updated to srem?, which will remove the associated warnings in the logs.
=> [SL-XX] update redis-namespace to version 1.11

app/services/recording_ready_notifier_service.rb, spec/services/recording_ready_notifier_service_spec.rb
fixes #971 
During the recording ready callback, the meetingID and recordingID should be signed using either the LOADBALANCER_SECRET or the secret for the given tenant.
=> Fix recording ready notifier in multitenancy

app/models/meeting.rb
Let Meeting.all return all meetings, regardless of tenant association, if tenant_id argument is not passed.
Previously, with Multitenancy enabled, Meeting.all would return only meetings without tenant association if the optional argument tenant_id was not passed. This leads to numerous bugs in the code, because the tenant_id argument is not passed in many cases. An example would be https://github.com/blindsidenetworks/scalelite/issues/1010 .
I propose to let Meeting.all return all meetings, regardless of tenant association, when it is called without tenant_id. In any case where only a certain tenant is considered, the tenant_id would have to be passed anyway. This fixes the issues with meetings remaining associated after panicking/disabling servers with Multitenancy enabled.
Test all the …
=> Let Meeting.all return all meetings if tenant_id argument is not passed

lib/tasks/servers.rake
Previously, the `servers` rake task would exit with status 0 when encountering a `RecordNotFound` error, which conventionally indicates a successful completion.
With this change, the task will now exit with status 1 when a `RecordNotFound` error occurs.
Fixes #999
=> fix: handle RecordNotFound with exit status 1 in rake servers

bigbluebutton/scalelite_post_publish.rb
current script removes tar even if transfer failed. using rsync option we have possibility to remove source in case transfer is successful only. if failed we can transfer failed tars later.
make test record with disconnected shared storage or temporary disabled destination.
<meeting_id.tar> file should stay in work_dir: /var/bigbluebutton/recording/scalelite
if destination is available tar file is not present in work_dir: /var/bigbluebutton/recording/scalelite after transfer.
=> delete source tar if transfer is successful only

lib/tasks/servers.rake
Add a guard in `rake servers:add` to return an error if the user does not include the protocol (http:// or https://) in the server url.
Not having the protocol in the url would cause an error when using Ruby `URI` method, for example when using `rake status`.
Fixes #996 and #997 
(try to) Add a server without the protocol in the url and it should return an error.
`rake servers:add['myhost.bbb.com','k2934k2934k9234']`
=> fix: add protocol guard to servers:add rake task

bigbluebutton/README.md, bigbluebutton/scalelite_prune_recordings
Having a dot in a filename prevents execution by cron when put under /etc/cron directories. Therefore, this PR removes the `.sh`extension from the filename. Also, a short README section is added.
See https://github.com/blindsidenetworks/scalelite/issues/1044 for further details regarding the cron behavior.
https://github.com/blindsidenetworks/scalelite/issues/1044
This will break any automated build scripts relying on the old filename to download the script from the repo. However, I assume in many cases they didn't rename the file and thus the script didn't do anything anyway.
=> Remove '.sh' from scalelite_prune_recordings such that it actually gets executed by cron

lib/tasks/status.rake
This PR prevent line wrapping within columns of the table outputted by the `rake status` task.
The Tabulo gem used to produce the table in the `rake status` task uses per default the terminal width as maximum table width when calling .pack() on the table before printing it: https://github.com/matt-harvey/tabulo#max-table-width
When the table content does not fit within this width, the gem will resort to line wrapping within columns to make the table fit. While this (very arguably) may be visually pleasing, it can unexpectedly break any kind of commands or scripts used on the output of `rake status`.
To prevent this behavior, `.pack()` is now called as follows: `.pack(max_table_width: nil)`.
https://github.com/blindsidenetworks/scalelite/issues/1020
=> Prevent column line wrapping in output of rake status task

lib/server_sync.rb, lib/tasks/servers.rake
Fixes multiple issues with the `rake servers:yaml` task.
The `rake servers:yaml` task had 3-4 bugs:
1) [Output of rake servers:yaml is incompatible to servers:sync ](https://github.com/blindsidenetworks/scalelite/issues/1057) This could in principle be fixed by specifying certain options in the YAML.safe_load call, but in my opinion it makes more sense to use strings for the keys. It is more human write-/readable and YAML.safe_load will work "out of the box".  This PR converts all the keys to strings.
2) [The value of "enabled" was always empty](https://github.com/blindsidenetworks/scalelite/issues/1024), because `servers.enabled` does not exist. It must be `servers.enabled?`, which is fixed by the PR.
3) The same mistake of 2) was also present in the logic behind the "state" value in the …
=> Fixes & improvements for servers:yaml rake task

app/models/server.rb
In server find_available, get server_load set only once and iterate through it until server with valid hash is found.
In server find_available, only retrieve the server_load via zrange once (but get the whole range instead of only first element) and iterate through it until a valid server is found. In my opinion this is a much more sane approach than the (kinda arbitrary) 5-times loop which always used the first element in the repeatedly obtained zrange. Furthermore, this would slim down the implementation in https://github.com/blindsidenetworks/scalelite/pull/1049.
Existing automated tests + testing in actual deployment.
- PR https://github.com/blindsidenetworks/scalelite/pull/1049 would be affected and need appropriate changes.
=> Improvements to loop in server find_available

app/controllers/api/servers_controller.rb, app/controllers/bigbluebutton_api_controller.rb, app/models/server.rb, app/services/server_update_service.rb, docs/api-README.md, docs/rake-README.md, docs/tags-README.md, lib/server_sync.rb, lib/tasks/servers.rake, lib/tasks/status.rake, spec/models/server_spec.rb, spec/requests/bigbluebutton_api_controller_spec.rb, spec/requests/servers_controller_spec.rb, test/controllers/bigbluebutton_api_controller_test.rb, test/models/server_test.rb
This PR implements a new feature called "Server Tags" or "Tagged Servers".
It is supposed to work as follows:
1. When adding a server in Scalelite, you can optionally specify a non-empty string as "tag" for the server. Per default, it is nil.
2. When making a "create" API call towards Scalelite, you can optionally pass a meta_server-tag string as parameter. If  passed, it will be handled as follows:
- If the last character of meta_server-tag is not a '!', the tag will will be intepreted as optional. The meeting will be created on the lowest load server with the corresponding tag, if any is available, or on the lowest load untagged (i.e. tag == nil) server otherwise.
- If the last character of meta_server-tag is a '!', this character will be stripped and the remaining tag will be …
=> Support for tagged servers (ready for review)

app/controllers/bigbluebutton_api_controller.rb, spec/requests/bigbluebutton_api_controller_spec.rb, test/controllers/bigbluebutton_api_controller_test.rb
During work on https://github.com/blindsidenetworks/scalelite/pull/1049, it turned out the handling of the create API call could use some improvements. These are especially useful in the context of the mentioned PR, but are independent of it.
Changes:
1) In bigbluebutton_api_controller.rb, begin with checking whether the meeting is already running and only when nothing is found, continue with find_available servers and meeting find_or_create_with_server. When an existing meeting is found, use the returned meeting information directly, instead of the same information that would have been returned from find_or_create_with_server.
This is mostly an improvement in terms of logic (e.g. allowing for 2) ) and also a performance improvement for the create call (which frontends may repeat before …
=> Improved handling of create API call

app/models/tenant.rb, app/services/lrs_payload_service.rb, lib/tasks/tenants.rake, spec/factories/tenant.rb, spec/services/lrs_payload_service_spec.rb
=> Changes to LRS Basic Authentication

Dockerfile, dockerfiles/v1/focal260-alpine, dockerfiles/v1/focal260-amazonlinux, nginx/playback/playback.nginx, nginx/playback/presentation-video.nginx, nginx/playback/presentation.nginx, nginx/playback/recording-screenshare.nginx
This PR fixes the protected recordings feature for all formats.
Protected recordings have been broken, i.e. unprotected paths were served by nginx, since at least SL v1.5. This has been reported in several issues.
The changes to nginx locations for presentation and video formats were originally proposed by @schrd in https://github.com/blindsidenetworks/scalelite/issues/983#issuecomment-1636724884
1) Generate a recording with all formats
2) transfer them to SL with protected recordings enabled
3) access them by clicking a format button in GL3
4) copy the (unprotected) recording URL from your browser into a different browser or private window
5) verify that you can't access the recording without token or cookie
~~**only the screenshare format is untested (of which I'm not sure if it …
=> Fix protected recordings

app/controllers/playback_controller.rb
This PR sets the Content-Disposition header for all formats without player, e.g. all formats except presentation, video and screenshare, to make them get downloaded to the device instead of playing in the browser. The header is purposefully *not* set via nginx locations, to preserve recording protection (if configured).
This PR was originally part of https://github.com/blindsidenetworks/scalelite/pull/1083 , arising from a confusion on my end. I was thinking that formats like podcast have the Content-disposition header set to attachment by default from the bbb-playback package, but in fact that was just a specialty that I have introduced to our deployment due to user requests to make certain formats more easily downloadable (we also have a "download" version of the video format).
There …
=> [Mod] Serve formats without player as downloadable attachments

app/services/recording_ready_notifier_service.rb, spec/services/recording_ready_notifier_service_spec.rb
fixes #1029
Add a "retry" mechanism to loop through all of the loadbalancer secrets when sending the recording ready notification service
Greenlight PR: https://github.com/bigbluebutton/greenlight/pull/5972
=> Add a retry mechanism for recording ready notifier

app/models/meeting.rb
For the solved problem, please refer to the extended description provided [here](https://github.com/blindsidenetworks/scalelite/issues/1120). This PR adds a hard-coded workaround (just rolling the dice again) for the default test_voice_bridge setting of 99999, which will match what is used in 99++% of BBB setups. In the rare case that this setting is changed to a non-default value, this workaround won't break anything (it will just avoid the particular voice bridge number of 99999).
I will open a separate issue to request an improved, configurable version of this workaround for the future (in case the underlying issue in BBB will not be fixed in the foreseeable future).
https://github.com/blindsidenetworks/scalelite/issues/1120
=> Workaround for voice_bridge=99999 (test_voice_bridge) issue

config/puma.rb
During merging of files in https://github.com/blindsidenetworks/scalelite/pull/1125 , a config block in `config/puma.rb` has accidentally been duplicated. This PR removes the duplication.
=> Remove duplicate block in config/puma.rb

.github/workflows/ci.build.prerelease.yml, .github/workflows/ci.build.push.master.yml, .github/workflows/ci.build.push.yml, .github/workflows/ci.build.release.yml, .rubocop.yml, Gemfile, app/controllers/concerns/cookie_same_site_compat.rb, app/models/application_redis_record.rb, dockerfiles/v1/focal260-amazonlinux, lib/redis_store.rb
Consistent Ruby version in Github workflows / rubocop (including trivial adaptions).
By working on GL3 I got remembered of the fact that the Ruby version is specified in more of the Github workflow files besides just the `ci.yml`, although the variable is not *obviously* used in any way in these files. Nevertheless, this PR makes the specified Ruby version consistent in these files. Also, the Ruby version target for Rubocop is adapted, including some trivial suggested changes.
The problem with the GitHub workflow files is also that there seems to be a lot of redundancy, but I'm not very familiar with the GitHub CI system since I'm generally using GitLab CI for test,build,push and thus won't touch that.
~~Another thing that apparently needs to be addressed is the whole amazonlinux build, …
=> Consistent Ruby version in GitHub workflows / rubocop + Fix amazonlinux build

app/models/server.rb, docs/tags-README.md, spec/models/server_spec.rb, test/models/server_test.rb
This PR enables support for semicolon-separated lists of tags as meta_server-tag argument in create calls, which then matches all servers with any of the tags in the list. It also introduces `none` as a special tag to explicitly reference untagged servers.
The following is a part of the updated documentation and describes how the feature works now:
A create API call using this feature is supposed to work as follows:
1) When making a "create" API call towards Scalelite, you can optionally pass a meta_server-tag parameter with a string value. The string can be a single tag or a semicolon-separated list of tags and may additionally contain a '!' as last character. It will be handled as follows:
2) If the last character of meta_server-tag is not a '!', the tags will will be intepreted as …
=> Support for semicolon-separated list of tags on create calls

app/models/meeting.rb, spec/models/meeting_spec.rb
solves #1161 
As a temporary fix, add a 24 hour expiry to meetings to solve the issue with obsolete meetings.
Long term, the poller will likely need to be adapted to handle this
=> Add meeting expiry to redis to remove obsolete entries
