blindsidenetworks/scalelite

README.md
=> BBBSL-45: Fixed typo in README

app/controllers/bigbluebutton_api_controller.rb
=> BBBSL-46: Delete meeting from database before sending end meeting call

Dockerfile
BBBSL-48: Fixed initialization to nil
=> BBBSL-48: Fixed initialization to nil

README.md, app/models/server.rb, lib/tasks/poll.rake, lib/tasks/servers.rake
With this changes a load-multiplier can be added to the servers. It will be multiplicated with the server-load.
Also added a small check for the parameters when adding servers
=> Load-multiplier to weight servers

README.md, app/models/server.rb, config/application.rb, lib/tasks/poll.rake, test/models/server_test.rb
=> BBBSL-50: Added healthy and unhealthy threshold for Poller

nginx/conf.d/scalelite-proxy.template, nginx/conf.d/scalelite-ssl.template, nginx/conf.d/scalelite.common, nginx/conf.d/scalelite.template
First 2 files are just formatting fixes
fixes #114
=> Increased default hash_bucket_size to 64

lib/tasks/poll.rake
=> Poller no longer changes server to enabled/disabled

app/models/server.rb, config/environments/development.rb, lib/tasks/poll.rake
=> Reset healthy/unhealthy counters so that only consecutive calls are counted

lib/tasks/poll.rake, lib/tasks/servers.rake
=> Unhealthy take down no longer disables a server

lib/tasks/servers.rake
=> Fixed issue causing panic task to reenable disabled servers

README.md, app/constraints/recording_constraint.rb, app/controllers/bigbluebutton_api_controller.rb, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/routes.rb, test/controllers/bigbluebutton_api_controller_test.rb, test/test_helper.rb
**Allow scalelite-api to run without Postgres:**
[Jira TASK LINK SL-56 ](https://blindsidenetworks.atlassian.net/secure/RapidBoard.jspa?rapidView=14&projectKey=SL&modal=detail&selectedIssue=SL-56&assignee=6005a6412b411b0076962588&assignee=UNASSIGNED_USER_ID)
[Jira TASK LINK SL-61 ](https://blindsidenetworks.atlassian.net/secure/RapidBoard.jspa?rapidView=14&projectKey=SL&modal=detail&selectedIssue=SL-61&assignee=6005a6412b411b0076962588&assignee=UNASSIGNED_USER_ID)
=> SL-56 & SL-61 : Add recording constraints

README.md, app/constraints/recording_constraint.rb, app/controllers/bigbluebutton_api_controller.rb, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/routes.rb, test/controllers/bigbluebutton_api_controller_test.rb, test/test_helper.rb
Reverts blindsidenetworks/scalelite#408
=> Revert "SL-56 & SL-61 : Add recording constraints"

README.md
=> SL-xx: Added /api to recommeded URL for frontend

.gitlab-ci.yml
Added script for publishing any branch to DockerHub. It requires DOCKERHUB_ALL_BRANCHES to be set.
=> added option for publishing any branch to dockerhub with gitlab ci

bin/start-poller, bin/start-recording-importer
added values by default to POLL_INTERVAL, RECORDING_IMPORT_POLL and RECORDING_IMPORT_POLL_INTERVAL
=> SL-79 SL-80 added value by default to env variables used on start scripts

config/application.rb, config/routes.rb, lib/recording_importer.rb, test/controllers/bigbluebutton_api_controller_test.rb
=> SL: 95, #471 Fix for undefined method `casecmp?' for nil:NilClass

app/controllers/bigbluebutton_api_controller.rb, test/controllers/bigbluebutton_api_controller_test.rb
=> SL:109, Handle get_meetings api in disabled servers

lib/recording_importer.rb
Should be merged only after https://github.com/blindsidenetworks/scalelite/pull/502
=> SL-85: Recordings that are reprocessed in BBB should override the one already imported in SL

README.md, app/controllers/bigbluebutton_api_controller.rb, app/controllers/concerns/bbb_errors.rb, app/models/server.rb, lib/tasks/poll.rake, lib/tasks/servers.rake, lib/tasks/status.rake, test/controllers/bigbluebutton_api_controller_test.rb, test/models/server_test.rb
New state for servers to retain existing meetings and not accept anymore meeting creation requests, ref: #500
=> SL:110: add cordon state

lib/tasks/servers.rake
=> SL-126: Display Server state in rake server task closes #550

lib/tasks/status.rake
=> SL-131: Server Offline status not shown correctly in server:status task 

app/controllers/bigbluebutton_api_controller.rb, test/controllers/bigbluebutton_api_controller_test.rb
- Filter getRecordings request based on meta parameters
- Filter getRecordings request based on the recording state
=> SL-129 & SL-130 Add filter for get_recordings api

app/handlers/analytics_callback_event_handler.rb
Fix for error while rejoining an existing meeting from moodle
=> SL-180 Update analytics_callback_event_handler.rb

lib/tasks/poll.rake
=> SL-152 Fix scalelite-poller crashing issue

README.md, config/application.rb, lib/recording_importer.rb
=> SL-145 Fix recording importer pg restart issue#239

lib/tasks/servers.rake
"panic" isn't able to clear meetings, when BBB-Server is down #598
=> SL-185: Update servers.rake

app/controllers/bigbluebutton_api_controller.rb, db/migrate/20210725200414_add_publish_updated_to_recordings.rb, db/schema.rb, lib/recording_importer.rb
Recording multiple formats publish un-publish issue
=> SL-193: Recording multiple formats publish un-publish issue

app/views/bigbluebutton_api/get_recordings.xml.builder, test/controllers/bigbluebutton_api_controller_test.rb
=> SL:187 Remove trailing / from recordings url

app/views/bigbluebutton_api/get_recordings.xml.builder, config/routes.rb, nginx/conf.d/scalelite.common
Update nginx conf for handling protected recordings in systemd
=> SL-194: Add nginx conf for systemd

app/controllers/bigbluebutton_api_controller.rb, test/controllers/bigbluebutton_api_controller_test.rb
=> SL-203: add getRecordings filter for meetingId/recordId

bigbluebutton/scalelite_batch_import.sh
use the group scalelite-spool when running command
=> SL-204: Update scalelite_batch_import.sh

config/routes.rb, test/controllers/bigbluebutton_api_controller_test.rb
=> SL-183: Fix for Problem joining meeting via Scalelite using POST

lib/recording_importer.rb
recordings are shown to the integrations even if the file does not exist
=> SL-211:  Fix the issue recordings importer issue 

.github/workflows/ci.yml, dockerfiles/v1/bionic230-amazonlinux
=> SL-215: updated amazonlinux base image

app/controllers/bigbluebutton_api_controller.rb, app/models/recording.rb, test/controllers/bigbluebutton_api_controller_test.rb
Reverts blindsidenetworks/scalelite#689
=> Revert "SL-213: Fix state updates for publish_recordings api"

README.md, lib/tasks/meetings.rake, lib/tasks/servers.rake
New rake tasks added for : 
`Update a server`
`List all meetingIds running in given servers`
`List all/specific meetings running in BigBlueButton servers`
`Get meeting details of a meeting running in BigBlueButton server`
`End all/specific meetings running in BigBlueButton servers`
Closes #235
=> SL-210: Add new rake tasks for managing servers and meetings!

lib/tasks/recordings.rake
=> GIT-722: Recording importer's failed import process does not retry (closes #722)

README.md, app/controllers/bigbluebutton_api_controller.rb, nginx/conf.d/scalelite-proxy.template, nginx/conf.d/scalelite-ssl.template, nginx/conf.d/scalelite.template, nginx/start
=> GIT-262: Apply PORT environment variable from etc/default/scalelite

app/controllers/bigbluebutton_api_controller.rb, app/models/recording.rb, test/controllers/bigbluebutton_api_controller_test.rb
There was a regression after some of the last PR were merged and this modification got lost. It is required to preserve the state=deleted as BBB does
=> SL-136 Add delete state to recordings

.gitignore
=> Added vscode and IDEA folders to git ignore

config/initializers/filter_parameter_logging.rb
=> Filtered out passwords from log files #757

dockerfiles/v1/bionic240-amazonlinux, nginx/nginx.repo
This is a follow-up PR after GIT-745 for fixing the Docker amazonlinux image that failed. It also updates the base amazonlinux image used to the latest February release.
=> GIT-745: follow-up commit for fixing amazonlinux image

Gemfile, Gemfile.lock, README.md, app/controllers/playback_controller.rb, app/views/errors/recording_not_found.html.erb, config/application.rb, config/locales/en.yml, public/recording_not_found.html, systemd/scalelite-api.service, test/controllers/playback_controller_test.rb
NOTE: Must be followed up with instructions and changes to `docker-compose.yml`
1. Go to `http://localhost:3000/recording/1234/test`
2. Notice the page title and error messages
3. Go to `config/locales/en.yml` and change one of the strings
4. Refresh your web page and confirm the strings have changed
=> Added translations to recording 404 page

README.md
=> Quick readme fix

Gemfile.lock, dockerfiles/v1/bionic240-amazonlinux
Updates to docker image based on amazonlinux to make work all the dependencies.
=> SL-242: updated amazonlinux base image (closes #826)

app/models/meeting.rb, app/models/playback_format.rb, app/models/server.rb
Some warning started to pop up in the logs after the last update.
=> SL-249: changed deprecated code styling claimed after redis gem update

.github/workflows/ci.build.prerelease.yml
=> SL-243: updated dockerfile image used for amazonlinux

Gemfile, Gemfile.lock
Downgraded ruby version to 3.0 so that it is compatible with the amazonlinux image
=> SL-272: reverted ruby version to 3.0

Dockerfile, nginx/conf.d/scalelite.common
closes #912 (hopefully :sweat_smile: )
=> SL-270: updated main dockerfile and added location for new formats

dockerfiles/v1/focal260-alpine, dockerfiles/v1/focal260-amazonlinux
=> SL-274: updated version of ruby in dockerfile

.github/workflows/ci.build.prerelease.yml, .github/workflows/ci.build.push.master.yml, .github/workflows/ci.build.push.yml, .github/workflows/ci.build.release.yml, .github/workflows/ci.yml
=> [CI] updates to scripts for github actions

app/controllers/bigbluebutton_api_controller.rb, spec/factories/meeting.rb, spec/requests/bigbluebutton_api_controller_spec.rb
=> SL-276: Added tests for multitenancy

README.md, app/controllers/concerns/api_helper.rb, config/application.rb, spec/controllers/concerns/api_helper_spec.rb, spec/requests/bigbluebutton_api_controller_spec.rb
=> SL-276: Final changes for multi-tenancy

config/application.rb, config/environments/production.rb
=> SL-276: Removed BASE_URL and replaced using logic with url_host

app/models/tenant.rb
=> SL-XX: Create new key name index if tenant name is updated, delete old

README.md, lib/tasks/recordings.rake
Added a task that allows for all existing recordings to be associated with a tenant. 
Addresses issue #938
=> SL-280: Add task to associate tenant id with all existing recordings

README.md, lib/tasks/status.rake, spec/requests/bigbluebutton_api_controller_spec.rb
1- Cleaned up the tests a bit
2- Solved warning with ServerInfo (fixes #939)
3- Fixed wrong links in README (fixes #944)
=> SL-XX: General cleanup and improvements

README.md, app/controllers/concerns/api_helper.rb, app/models/tenant_setting.rb, lib/tasks/tenant_settings.rake, spec/controllers/concerns/api_helper_spec.rb, spec/factories/tenant_setting.rb, spec/models/tenant_setting_spec.rb, spec/requests/bigbluebutton_api_controller_spec.rb
=> Implemented tenant settings which allows different create/join params for each tenant

app/controllers/api/v1/tenants_controller.rb, config/routes.rb, spec/requests/tenants_controller_spec.rb
In order to get full usage of the new Multitenancy Feature, API access was implemented to allow easier management of Tenants without having to rely on SSH access to access Rake tasks.
New API endpoints implemented:
api/v1/tenants/ => api/v1/tenants_controller
- GET api/v1/tenants/
- GET api/v1/tenants/:id
- POST api/v1/tenants/:id?name=xxx&secrets=xxx
- DELETE api/v1/tenants/:id
- PUT api/v1/tenants/:id?name=xxx || PUT api/v1/tenants/:id?secrets=xxx
Run the associated spec file, or make the API requests using cURL or another tool.
=> SL-252: API to manage tenants

README.md, lib/tasks/tenants.rake, spec/tasks/tenants_task_spec.rb
fixes #946 
1- Create a tenant
2- Verify tenant with `rake tenants`
3- Update either name or secret using `rake tenants:update[tenant_id,name,secrets]
4- Verify new tenant values with `rake tenants`
=> SL-XX: Added tenant update rake task

app/controllers/servers_controller.rb, app/services/server_update_service.rb, config/routes.rb, spec/factories/meeting.rb, spec/requests/servers_controller_spec.rb, spec/services/server_update_service_spec.rb
- Add `Servers` controller based on the servers.rake tasks
- Add `ServerUpdate` service
- Add Servers routes for `/API/v1/`
- Add Servers specs
- Review Error handling please
=> Add Servers API: controller, routes, service, specs

app/controllers/api/tenants_controller.rb, docs/api-README.md
Update the comments and documentation to account for the scoping of the request params
=> SL-xx: Scope Tenants and Servers request params

db/migrate/20230627141045_drop_tenants.rb, db/schema.rb
Snuck through from the changes before refactor. The Postgres table isn't needed, only the redis one
=> Drop unneeded tenants table

app/controllers/concerns/api_helper.rb, app/services/recording_ready_notifier_service.rb, spec/controllers/concerns/api_helper_spec.rb, spec/services/recording_ready_notifier_service_spec.rb
=> Another try at fixing recording notifier

app/controllers/bigbluebutton_api_controller.rb
=> Another take at fixing getRecordings call

config/application.rb
=> Fix issue causing MT to be enabled when it shouldnt

app/controllers/bigbluebutton_api_controller.rb
=> Fix issue causing duplicate recordings

spec/models/meeting_spec.rb
=> Fix failing rspecs

lib/tasks/poll.rake
=> Fix issue that would cause the poller not to panic correctly

.rubocop.yml, app/controllers/bigbluebutton_api_controller.rb, app/models/tenant.rb, app/services/lrs_payload_service.rb, lib/tasks/tenants.rake, spec/factories/tenant.rb, spec/requests/bigbluebutton_api_controller_spec.rb, spec/services/lrs_payload_service_spec.rb
=> Initial work for custom lrs integration

app/models/tenant.rb, app/services/lrs_payload_service.rb, lib/tasks/tenants.rake, spec/factories/tenant.rb, spec/services/lrs_payload_service_spec.rb
=> Added basic authentication for LRS endpoint

docs/rake-README.md
=> Added LRS details to docs

.rubocop.yml, spec/requests/servers_controller_spec.rb
These changes will be required to fix RSpec and rubocop when https://github.com/blindsidenetworks/scalelite/releases/tag/v1.5.2 is merged into master.
=> Prepare RSpec and rubocop.yml for merge of v1.5.2

Gemfile.lock
=> Fix gemfile.lock

.github/workflows/ci.build.push.master.yml
=> Fix alternate builds

.github/workflows/ci.build.prerelease.yml, .github/workflows/ci.build.push.master.yml, .github/workflows/ci.build.push.yml, .github/workflows/ci.build.release.yml
=> More fixes for alternate builds

lib/recording_importer.rb
=> Fix key that files are being store under
